CSE_site/CSE_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', views.landing_page, name='landing_page'),
    path('exam_room_allocator/', include('online_cie_allocator.urls')),
    path('', include('authentication.urls')),
    path('notes_and_qp_mgmt/', include('notes_and_qp_mgmt.urls')),
    path('student/', include('student_dashboard_proctor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CSE_site/office_dashboard_proctor/urls.py
from django.urls import path,include
from . import views

app_name = 'office'

urlpatterns = [
    path('/dashboard/', views.dashboard, name="dashboard"),
    path('/proctor-assign', views.proctor_assign, name='proctor-assign'),
    path('/download-excel/', views.download_excel, name='download-excel'),
    path('/view-students/<str:pk>', views.view_students, name='view-proctor-students'),

]

CSE_site/office_dashboard_proctor/models.py
from django.db import models

# Create your models here.
class Office(models.Model):
    name = models.CharField(max_length=200)
    email=models.EmailField()
    
    class Meta:
        ordering = ['name']
        
    def __str__(self):
        return self.name

CSE_site/office_dashboard_proctor/views.py
from django.shortcuts import render, redirect, HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .models import Office
from student_dashboard_proctor.models import Student, StudentDetail, Sem, Fastrack
from faculty_dashboard_proctor.models import Faculty
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.conf import settings
import openpyxl
import pandas as pd


@login_required
def dashboard(request):
    office = Office.objects.get(email=request.user.email)
    faculty = Faculty.objects.all()
    context = {'office': office, 'faculties': faculty}
    return render(request, 'office_dashboard_proctor/dashboard.html', context)


def proctor_assign(request):
    if request.method == "POST":
        excel_file = request.FILES['excel']
        df = pd.read_excel(excel_file)
        for index, row in df.iterrows():
            std_usn = row['USN']
            proctor_email = row['Proctor Email']
            std_sem = int(row['Sem'])
            try:
                student = Student.objects.get(USN=std_usn)
                proctor = Faculty.objects.get(email=proctor_email)
                student.proctor_id = proctor
                student.current_sem=std_sem
                student.save()
            except (Student.DoesNotExist, Faculty.DoesNotExist):
                pass
        return redirect('office:dashboard')
    return render(request, 'office_dashboard_proctor/proctor_assign.html')



def download_excel(request):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws['A1'] = 'Sl. No.'
    ws['B1'] = 'USN'
    ws['C1'] = 'Name'
    ws['D1'] = 'Email'
    ws['E1'] = 'Proctor Name'
    ws['F1'] = 'Proctor Email'
    ws['G1'] = 'Sem'
    filename = 'proctor_assignment_sheet.xlsx'
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    wb.save(response)
    return response

def view_students(request,pk):
    faculty=Faculty.objects.get(email=pk)
    students=Student.objects.filter(proctor_id=faculty)
    context = {'students':students,'faculty':faculty}
    return render(request,'office_dashboard_proctor/view_students.html',context)

# def remove_student(request,pk):

CSE_site/templates/office_dashboard_proctor/dashboard.html
{% extends '../base.html' %} {% load static %} {% block content %}
<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }

  .b-example-divider {
    height: 3rem;
    background-color: rgba(0, 0, 0, 0.1);
    border: solid rgba(0, 0, 0, 0.15);
    border-width: 1px 0;
    box-shadow: inset 0 0.5em 1.5em rgba(0, 0, 0, 0.1),
      inset 0 0.125em 0.5em rgba(0, 0, 0, 0.15);
  }

  .b-example-vr {
    flex-shrink: 0;
    width: 1.5rem;
    height: 100vh;
  }

  .bi {
    vertical-align: -0.125em;
    fill: currentColor;
  }

  .nav-scroller {
    position: relative;
    z-index: 2;
    height: 2.75rem;
    overflow-y: hidden;
  }

  .nav-scroller .nav {
    display: flex;
    flex-wrap: nowrap;
    padding-bottom: 1rem;
    margin-top: -1px;
    overflow-x: auto;
    text-align: center;
    white-space: nowrap;
    -webkit-overflow-scrolling: touch;
  }
  .feather {
    width: 16px;
    height: 16px;
  }

  /*
        * Sidebar
        */

  .sidebar {
    position: fixed;
    top: 0;
    /* rtl:raw:
        right: 0;
        */
    bottom: 0;
    /* rtl:remove */
    left: 0;
    z-index: 100; /* Behind the navbar */
    padding: 48px 0 0; /* Height of navbar */
    box-shadow: inset -1px 0 0 rgba(0, 0, 0, 0.1);
  }

  @media (max-width: 767.98px) {
    .sidebar {
      top: 5rem;
    }
  }

  .sidebar-sticky {
    height: calc(100vh - 48px);
    overflow-x: hidden;
    overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
  }

  .sidebar .nav-link {
    font-weight: 500;
    color: #333;
  }

  .sidebar .nav-link .feather {
    margin-right: 4px;
    color: #727272;
  }

  .sidebar .nav-link.active {
    color: #2470dc;
  }

  .sidebar .nav-link:hover .feather,
  .sidebar .nav-link.active .feather {
    color: inherit;
  }

  .sidebar-heading {
    font-size: 0.75rem;
  }

  /*
        * Navbar
        */

  .navbar-brand {
    padding-top: 0.75rem;
    padding-bottom: 0.75rem;
    background-color: rgba(0, 0, 0, 0.25);
    box-shadow: inset -1px 0 0 rgba(0, 0, 0, 0.25);
  }

  .navbar .navbar-toggler {
    top: 0.25rem;
    right: 1rem;
  }

  .navbar .form-control {
    padding: 0.75rem 1rem;
  }

  .form-control-dark {
    color: #fff;
    background-color: rgba(255, 255, 255, 0.1);
    border-color: rgba(255, 255, 255, 0.1);
  }

  .form-control-dark:focus {
    border-color: transparent;
    box-shadow: 0 0 0 3px rgba(255, 255, 255, 0.25);
  }
  .notification {
    color: white;
    text-decoration: none;
    padding: 15px 26px;
    position: relative;
    display: inline-block;
  }

  .notification .badge {
    position: absolute;
    top: -10px;
    right: -10px;
    padding: 5px 10px;
    border-radius: 50%;
    background-color: red;
    color: white;
  }
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }

  td,
  th {
    border: 1px solid #eef3fe;
    text-align: left;
    padding: 8px;
  }

  tr:nth-child(even) {
    background-color: #e0e6f9;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md bg-light">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="office:dashboard">
            <span data-feather="home" class="align-text-bottom"></span>
            Dashboard
          </a>
        </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'office:proctor-assign' %}">
              <span data-feather="file" class="align-text-bottom"></span>
              Assign Proctor
            </a>
          </li>
      </ul>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="main_details">
            <span width="50%"><h5>Name : {{office.name}}</h5></span>
            <span width="50%"><h5>Email : {{office.email}}</h5></span>
          </div>
          <br>
          <hr>
          <h5>Proctor List</h5>
          <br />
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th scope="col">Sl.no</th>
                  <th scope="col">Name</th>
                  <th scope="col">Email</th>
                  <th scope="col">Designation</th>
                  <th scope="col">View Students</th>
                </tr>
              </thead>
              
                <tbody>
                  {% for faculty in faculties %}
                  <tr>
                    
                    <td>{{forloop.counter}}</td>
                    <td>{{faculty.name}}</td>
                    <td>{{faculty.email}}</td>
                    <td>{{faculty.designation}}</td>
                    <td><a href="{% url 'office:view-proctor-students' faculty.email %}" style="cursor: pointer; text-decoration: none;">View</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              
            </table>
          </div>
    </main>
  </div>
</div>

{% endblock content %}

CSE_site/templates/office_dashboard_proctor/proctor_assign.html
{% extends '../base.html' %}
{% load static %}

{% block content %}


<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }
    
    th, td {
        text-align: left;
        padding: 8px;
    }
    
    th {
        background-color: #1b62bf;
        color: white;
    }
    
    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
    
    h3 {
        margin-top: 20px;
    }
    
    .note {
        margin-top: 20px;
        margin-bottom: 20px;
    }
    
    .note p {
        margin-bottom: 10px;
    }
    
    .btn {
        background-color: #1b62bf;
        border: none;
        border-radius: 5px;
        color: white;
        padding: 10px 20px;
        text-decoration: none;
        display: inline-block;
        margin-top: 20px;
    }
    
    .btn:hover {
        background-color: #16579e;
    }
    
    .position {
        position: relative;
    }
    
    .position input {
        padding-left: 40px;
    }
    
    .position .fa-upload {
        position: absolute;
        top: 10px;
        left: 10px;
        font-size: 20px;
    }
    
</style>

<h3 style="color:red;">Note:</h3>
<div class="note">
    <p>1: The excel sheet should follow the below format:</p>
    <table>
        <thead>
            <tr>
                <th>Sl. No.</th>
                <th>USN</th>
                <th>Name</th>
                <th>Email</th>
                <th>Proctor Name</th>
                <th>Proctor Email</th>
                <th>Sem</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>1BM20CS000</td>
                <td>xxx</td>
                <td>xxx.cs20@bmsce.ac.in</td>
                <td>yyy</td>
                <td>yyy.cse@bmsce.ac.in</td>
                <td>5</td>
            </tr>
        </tbody>
    </table>
    <p>2: Download the excel sheet format from the given link below:</p>
    <a href="{% url 'office:download-excel' %}" class="btn">Download Template</a>
    <p style="color:red;">3: All the teachers (proctors) and students must be registered in the website  !IMPORTANT</p>
</div>

<form method="post" style="margin-left: 20%;" action="{% url 'office:proctor-assign' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="position" style="margin-bottom: 1%; width: 80%;">
        <i class="fa fa-upload"></i>
        <input class="form-control border" name='excel' type="file" id="exampleInputEmail1" aria-describedby="emailHelp">
        <br/>
        <div>
            <button class="btn" type="submit">Upload</button>
        </div>
    </div>
</form>

{% endblock content %}

CSE_site/templates/office_dashboard_proctor/view_students.html
{% extends '../base.html' %} {% load static %} {% block content %}
<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }

  .b-example-divider {
    height: 3rem;
    background-color: rgba(0, 0, 0, 0.1);
    border: solid rgba(0, 0, 0, 0.15);
    border-width: 1px 0;
    box-shadow: inset 0 0.5em 1.5em rgba(0, 0, 0, 0.1),
      inset 0 0.125em 0.5em rgba(0, 0, 0, 0.15);
  }

  .b-example-vr {
    flex-shrink: 0;
    width: 1.5rem;
    height: 100vh;
  }

  .bi {
    vertical-align: -0.125em;
    fill: currentColor;
  }

  .nav-scroller {
    position: relative;
    z-index: 2;
    height: 2.75rem;
    overflow-y: hidden;
  }

  .nav-scroller .nav {
    display: flex;
    flex-wrap: nowrap;
    padding-bottom: 1rem;
    margin-top: -1px;
    overflow-x: auto;
    text-align: center;
    white-space: nowrap;
    -webkit-overflow-scrolling: touch;
  }
  .feather {
    width: 16px;
    height: 16px;
  }

  /*
        * Sidebar
        */

  .sidebar {
    position: fixed;
    top: 0;
    /* rtl:raw:
        right: 0;
        */
    bottom: 0;
    /* rtl:remove */
    left: 0;
    z-index: 100; /* Behind the navbar */
    padding: 48px 0 0; /* Height of navbar */
    box-shadow: inset -1px 0 0 rgba(0, 0, 0, 0.1);
  }

  @media (max-width: 767.98px) {
    .sidebar {
      top: 5rem;
    }
  }

  .sidebar-sticky {
    height: calc(100vh - 48px);
    overflow-x: hidden;
    overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
  }

  .sidebar .nav-link {
    font-weight: 500;
    color: #333;
  }

  .sidebar .nav-link .feather {
    margin-right: 4px;
    color: #727272;
  }

  .sidebar .nav-link.active {
    color: #2470dc;
  }

  .sidebar .nav-link:hover .feather,
  .sidebar .nav-link.active .feather {
    color: inherit;
  }

  .sidebar-heading {
    font-size: 0.75rem;
  }

  /*
        * Navbar
        */

  .navbar-brand {
    padding-top: 0.75rem;
    padding-bottom: 0.75rem;
    background-color: rgba(0, 0, 0, 0.25);
    box-shadow: inset -1px 0 0 rgba(0, 0, 0, 0.25);
  }

  .navbar .navbar-toggler {
    top: 0.25rem;
    right: 1rem;
  }

  .navbar .form-control {
    padding: 0.75rem 1rem;
  }

  .form-control-dark {
    color: #fff;
    background-color: rgba(255, 255, 255, 0.1);
    border-color: rgba(255, 255, 255, 0.1);
  }

  .form-control-dark:focus {
    border-color: transparent;
    box-shadow: 0 0 0 3px rgba(255, 255, 255, 0.25);
  }
  .notification {
    color: white;
    text-decoration: none;
    padding: 15px 26px;
    position: relative;
    display: inline-block;
  }

  .notification .badge {
    position: absolute;
    top: -10px;
    right: -10px;
    padding: 5px 10px;
    border-radius: 50%;
    background-color: red;
    color: white;
  }
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }

  td,
  th {
    border: 1px solid #eef3fe;
    text-align: left;
    padding: 8px;
  }

  tr:nth-child(even) {
    background-color: #e0e6f9;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md bg-light">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">
            <span data-feather="home" class="align-text-bottom"></span>
            Dashboard
          </a>
        </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'office:proctor-assign' %}">
              <span data-feather="file" class="align-text-bottom"></span>
              Assign Proctor
            </a>
          </li>
      </ul>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="main_details">
            <span width="50%"><h5>Name : {{faculty.name}}</h5></span>
            <span width="50%"><h5>Email : {{faculty.email}}</h5></span>
            <span width="50%"><h5>Designation : {{faculty.designation}}</h5></span>
          </div>
          <br>
          <hr>
          <h5>Students List</h5>
          <br />
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th scope="col">Sl.no</th>
                  <th scope="col">Name</th>
                  <th scope="col">Email</th>
                  <th scope="col">Semester</th>
                </tr>
              </thead>
              
                <tbody>
                  {% for student in students %}
                  <tr>
                    
                    <td>{{forloop.counter}}</td>
                    <td>{{student.name}}</td>
                    <td>{{student.email}}</td>
                    <td>{{student.current_sem}}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              
            </table>
          </div>
    </main>
  </div>
</div>

{% endblock content %}