CSE_site/CSE_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', views.landing_page, name='landing_page'),
    path('exam_room_allocator/', include('online_cie_allocator.urls')),
    path('', include('authentication.urls')),
    path('notes_and_qp_mgmt/', include('notes_and_qp_mgmt.urls')),
    path('student/', include('student_dashboard_proctor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CSE_site/faculty_dashboard_proctor/urls.py
from django.urls import path,include
from . import views

app_name = 'faculty'

urlpatterns = [
    path('/dashboard/', views.dashboard, name="dashboard"),
    path('/student/<str:pk>', views.studentDetails, name="student-details"),
    path('/student/approved/<str:pk>', views.approve, name="student-details-approve"),
    path('/student/approved/<str:pk>/<str:course_id>', views.courseApprove, name="student-course-approve"),
    path('/student/reject/<str:emails>', views.courseReject, name='student-course-reject'),
    path('/student/fapproved/<str:pk>/<str:course_id>', views.courseApproveFast, name="student-fcourse-approve"),
    path('/student/freject/<str:emails>', views.courseRejectFast, name='student-fcourse-reject'),
    path('/add-students', views.addStudents, name='add-students'),
    path('/add-marks', views.addMarks, name='add-marks'),
    path('/send-register-form', views.sendCourse, name='send-register-form'),
    path('/student/alert/<str:emails>', views.sendAlertMail, name='student-alert'),
    path('/send-email-parent', views.sendParents, name="send-parents"),
    path('/send-email-custom', views.writeEmail, name='custom-email'),
    path('/email-form', views.customMail, name='custom-form'),
    path('/add-marks-fast', views.addfastMarks, name='add-marks-fast')
]

CSE_site/student_dashboard_proctor/urls.py
from django.urls import path,include
from . import views

app_name = 'student'

urlpatterns = [
    path('/dashboard/<str:pk>/', views.dashboard, name="dashboard"),
    path('/marks/<str:pk>/', views.dashboard_marks, name="marks"),
    path('/courses/register/', views.registerCourses, name='register'),
    path('/add_student_details/', views.studentDetails, name='student_details_form'),
    path('/courses/edit/', views.editCourseDetails, name='edit'),
    path('/courses/update/', views.updateCourseDetails, name='update'),
    path("/no_proctor", views.no_proc, name="no_proctor"),
    path("/courses/fastrack/register", views.registerFastrack, name="fastrack_register"),
]

CSE_site/faculty_dashboard_proctor/models.py
from django.db import models

# Create your models here.
class Faculty(models.Model):
    name = models.CharField(max_length=200)
    email=models.EmailField()
    designation = models.CharField(max_length=200)
    
    class Meta:
        ordering = ['name']
        
    def __str__(self):
        return self.name

CSE_site/faculty_dashboard_proctor/views.py
from django.shortcuts import render, redirect, HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import Faculty
from student_dashboard_proctor.models import Student, StudentDetail, Sem, Fastrack, courseRequest
from django.template.loader import render_to_string
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.conf import settings
import openpyxl
import pandas as pd
from django.template.loader import get_template
from django.template import Context

# Create your views here.
@login_required
def dashboard(request):
    faculty = Faculty.objects.get(email=request.user.email)
    students = Student.objects.filter(proctor_id=faculty)
    context = {'faculty': faculty, 'students': students}
    return render(request, 'faculty_dashboard_proctor/dashboard.html', context)

def sendFillMail(request, message, name, emails):
    template = render_to_string('faculty_dashboard_proctor/send_fill.html', {'message': message, 'name': name})
    email = EmailMessage(
                message,
                template,
                settings.EMAIL_HOST_USER,
                [emails],
                # fail_silently=False,
            )
    email.send()

def studentDetails(request, pk):
    if StudentDetail.objects.filter(USN=pk).exists():
        s_info = StudentDetail.objects.get(USN=pk)
    else :
        s_info = 0
    student = Student.objects.get(USN=pk)
    if request.method == 'POST':
        message = request.POST['email-text']
        sendFillMail(request, message, 'Sudeep' ,student.email)
        return redirect('faculty:dashboard')
    courses = Sem.objects.filter(sem=student.current_sem, USN=pk)
    not_ap = False
    for co in courses:
        if not co.is_approved:
            not_ap = True
    if courses.exists():
        cour = True
        marks = courses[0].CIE == None
    else:
        cour = False
        marks = False
    fastrack = Fastrack.objects.filter(USN=pk, is_active=True)
    length = fastrack.count()
    request.session['current_usn'] = pk
    context = {'s_info': s_info,'not_ap': not_ap, 'courses': courses, 'fastrack': fastrack, 'fast_count': length, 'email': student.email, 'usn': student.USN, 'marks': marks, 'cour': cour, 'sem': student.current_sem}
    return render(request, 'faculty_dashboard_proctor/student_details.html', context)

def approve(request, pk):
    s_info = StudentDetail.objects.get(USN=pk)
    s_info.isApproved = True
    s_info.save()
    return redirect('faculty:student-details', pk=pk)

def courseApprove(request, pk, course_id):
    print(type(course_id))
    if course_id == "0":
        courses = Sem.objects.filter(USN=pk, is_active=True)
        for course in courses:
            course.is_approved = True
            course.save()
    else:
        course = Sem.objects.get(USN=pk, courseCode=course_id)
        course.is_approved = True
        course.save()
    return redirect('faculty:student-details', pk=pk)

def courseApproveFast(request, pk, course_id):
    print(course_id)
    if course_id == "0":
        courses = Fastrack.objects.filter(USN=pk, is_active=True)
        for course in courses:
            sem_ob = Sem.objects.get(USN=pk, courseCode=course.courseCode)
            sem_ob.attemptNumber = sem_ob.attemptNumber + 1
            sem_ob.save()
            course.is_approved = True
            course.save()
    else:
        print(course_id)
        course = Fastrack.objects.get(USN=pk, courseCode=course_id)
        sem_ob = Sem.objects.get(USN=pk, courseCode=course.courseCode)
        sem_ob.attemptNumber = sem_ob.attemptNumber + 1
        sem_ob.save()
        course.is_approved = True
        course.save()
    return redirect('faculty:student-details', pk=pk)

def courseReject(request, emails):
    student=Student.objects.get(email=emails)
    message = 'Looks like there is a mistake in your registered courses, check out the unapproved courses and update it'
    faculty = Faculty.objects.get(email=request.user.email)
    name = faculty.name
    template = render_to_string('faculty_dashboard_proctor/send_fill.html', {'message': message, 'name': name})
    email = EmailMessage(
        
                message,
                template,
                settings.EMAIL_HOST_USER,
                [emails],
                # fail_silently=False,
                
            )
    email.send()
    return redirect('faculty:student-details', pk=student.USN)

def courseRejectFast(request, emails):
    student=Student.objects.get(email=emails)
    message = 'Looks like there is a mistake in your registered courses, check out the unapproved courses and update it'
    faculty = Faculty.objects.get(email=request.user.email)
    name = faculty.name
    template = render_to_string('faculty_dashboard_proctor/send_fill.html', {'message': message, 'name': name})
    email = EmailMessage(
        
                message,
                template,
                settings.EMAIL_HOST_USER,
                [emails],
                # fail_silently=False,
                
            )
    email.send()
    return redirect('faculty:student-details', pk=student.USN)

def addStudents(request):
    if request.method == "POST":
        excel_file = request.FILES['excel']
        print(excel_file)
        wb = pd.read_excel(excel_file)
        usn = []
        sem = []
        total = len(wb['USN'])
        for i in range(total):
            usn.append(wb['USN'][i])
            sem.append(wb['Sem'][i])
        faculty = Faculty.objects.get(email=request.user.email)   
        for usns, sems in zip(usn, sem):
            student = Student.objects.get(USN=usns)
            student.proctor_id = faculty
            student.current_sem = sems
            student.save()
        return redirect('faculty:dashboard')
    return render(request, 'faculty_dashboard_proctor/add_students.html')

def sendCourse(request):
    if request.method == "POST":
        faculty = Faculty.objects.get(email=request.user.email)
        students = Student.objects.filter(proctor_id=faculty, current_sem=int(request.POST['sems'])-1)
        emails= []
        for stud in students:
            emails.append(stud.email)
            req = courseRequest()
            req.faculty = faculty
            req.sem = int(request.POST['sems'])
            req.no_subjects = request.POST['subjects']
            req.student_usn = stud.USN
            req.save()
            stud.current_sem = int(request.POST['sems'])
            stud.save()
            courses = Sem.objects.filter(USN=stud.USN, sem=stud.current_sem-1, is_active=True)
            for course in courses:
                course.is_active = False
                course.save()
        message = "Fill the course registration form as soon as possible"
        name = faculty.name
        template = render_to_string('faculty_dashboard_proctor/send_fill.html', {'message': message, 'name': name})
        email = EmailMessage(
                message,
                template,
                settings.EMAIL_HOST_USER,
                emails,
            )
        email.send()
        return redirect('faculty:dashboard')
    return render(request, 'faculty_dashboard_proctor/course_register.html')

def sendAlertMail(request, emails):
    student=Student.objects.get(email=emails)
    message = 'Looks like you have not filled the course registration. Please fill ASAP'
    faculty = Faculty.objects.get(email=request.user.email)
    name = faculty.name
    template = render_to_string('faculty_dashboard_proctor/send_fill.html', {'message': message, 'name': name})
    email = EmailMessage(
        
                message,
                template,
                settings.EMAIL_HOST_USER,
                [emails],
                # fail_silently=False,
                
            )
    email.send()
    return redirect('faculty:dashboard')

def addMarks(request):
    if request.method == "POST":
        excel_file = request.FILES['excel']
        print(excel_file)
        wb = pd.read_excel(excel_file)
        i=0
        usns = []
        for usn in wb['USN']:
            if i==0:
                i+=1
                continue
            i+=1
            usns.append(usn)
        
        for i in range(0, len(usns)):
            for cols in wb.columns:
                if cols == 'USN':
                    continue
                if not('Unnamed' in cols):
                    curr_col = "".join(cols.rstrip())
                print(curr_col)
                if Sem.objects.filter(USN=usns[i], courseCode=str(curr_col)).exists():
                    sem = Sem.objects.get(USN=usns[i], courseCode=str(curr_col))
                    if wb[cols][0] == 'CIE':
                        sem.CIE = wb[cols][i+1]
                    if wb[cols][0] == 'SEE':
                        sem.SEE = wb[cols][i+1]
                    if wb[cols][0] == 'Grade':
                        sem.GradePoints = wb[cols][i+1]
                    if wb[cols][0] == 'Attendance':
                        sem.attendance = wb[cols][i+1]
                    sem.save()
        return redirect('faculty:dashboard')
    return render(request, 'faculty_dashboard_proctor/add_marks.html')

def sendParents(req):
    faculty = Faculty.objects.get(email=req.user.email)
    students = Student.objects.filter(proctor_id=faculty)
    name = faculty.name
    designation = faculty.designation
    for student in students:
        marks = Sem.objects.filter(USN=student.USN, sem=student.current_sem-1)
        det = StudentDetail.objects.get(USN=student.USN)
        par_email = det.father_email
        subject = 'Marks Update'
        message = 'Dear Parent, please find the marks of '+student.name+' for the sem '+str(student.current_sem-1)
        content = {'message': message, 'name': name, 'designation': designation, 'courses': marks}
        htmly     = get_template('faculty_dashboard_proctor/send_marks_email.html')

CSE_site/templates/faculty_dashboard_proctor/dashboard.html
{% extends '../base.html' %} {% load static %} {% block content %}
<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }

  .b-example-divider {
    height: 3rem;
    background-color: rgba(0, 0, 0, 0.1);
    border: solid rgba(0, 0, 0, 0.15);
    border-width: 1px 0;
    box-shadow: inset 0 0.5em 1.5em rgba(0, 0, 0, 0.1),
      inset 0 0.125em 0.5em rgba(0, 0, 0, 0.15);
  }

  .b-example-vr {
    flex-shrink: 0;
    width: 1.5rem;
    height: 100vh;
  }

  .bi {
    vertical-align: -0.125em;
    fill: currentColor;
  }

  .nav-scroller {
    position: relative;
    z-index: 2;
    height: 2.75rem;
    overflow-y: hidden;
  }

  .nav-scroller .nav {
    display: flex;
    flex-wrap: nowrap;
    padding-bottom: 1rem;
    margin-top: -1px;
    overflow-x: auto;
    text-align: center;
    white-space: nowrap;
    -webkit-overflow-scrolling: touch;
  }
  .feather {
    width: 16px;
    height: 16px;
  }

  /*
        * Sidebar
        */

  .sidebar {
    position: fixed;
    top: 0;
    /* rtl:raw:
        right: 0;
        */
    bottom: 0;
    /* rtl:remove */
    left: 0;
    z-index: 100; /* Behind the navbar */
    padding: 48px 0 0; /* Height of navbar */
    box-shadow: inset -1px 0 0 rgba(0, 0, 0, 0.1);
  }

  @media (max-width: 767.98px) {
    .sidebar {
      top: 5rem;
    }
  }

  .sidebar-sticky {
    height: calc(100vh - 48px);
    overflow-x: hidden;
    overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
  }

  .sidebar .nav-link {
    font-weight: 500;
    color: #333;
  }

  .sidebar .nav-link .feather {
    margin-right: 4px;
    color: #727272;
  }

  .sidebar .nav-link.active {
    color: #2470dc;
  }

  .sidebar .nav-link:hover .feather,
  .sidebar .nav-link.active .feather {
    color: inherit;
  }

  .sidebar-heading {
    font-size: 0.75rem;
  }

  /*
        * Navbar
        */

  .navbar-brand {
    padding-top: 0.75rem;
    padding-bottom: 0.75rem;
    background-color: rgba(0, 0, 0, 0.25);
    box-shadow: inset -1px 0 0 rgba(0, 0, 0, 0.25);
  }

  .navbar .navbar-toggler {
    top: 0.25rem;
    right: 1rem;
  }

  .navbar .form-control {
    padding: 0.75rem 1rem;
  }

  .form-control-dark {
    color: #fff;
    background-color: rgba(255, 255, 255, 0.1);
    border-color: rgba(255, 255, 255, 0.1);
  }

  .form-control-dark:focus {
    border-color: transparent;
    box-shadow: 0 0 0 3px rgba(255, 255, 255, 0.25);
  }
  .notification {
    color: white;
    text-decoration: none;
    padding: 15px 26px;
    position: relative;
    display: inline-block;
  }

  .notification .badge {
    position: absolute;
    top: -10px;
    right: -10px;
    padding: 5px 10px;
    border-radius: 50%;
    background-color: red;
    color: white;
  }
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }

  td,
  th {
    border: 1px solid #eef3fe;
    text-align: left;
    padding: 8px;
  }

  tr:nth-child(even) {
    background-color: #e0e6f9;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md bg-light">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">
            <span data-feather="home" class="align-text-bottom"></span>
            Dashboard
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'faculty:add-marks' %}">
            <span data-feather="file" class="align-text-bottom"></span>
            Update Marks
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'faculty:add-marks-fast' %}">
            <span data-feather="file" class="align-text-bottom"></span>
            Update Fastrack Marks
          </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'faculty:send-register-form' %}">
              <span data-feather="file" class="align-text-bottom"></span>
              Course Registration Form
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'faculty:add-students' %}">
              <span data-feather="file" class="align-text-bottom"></span>
              Add Students
            </a>
          </li>
      </ul>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="main_details">
            <span width="50%"><h5>Name : {{faculty.name}}</h5></span>
            <span width="50%"><h5>Email : {{faculty.email}}</h5></span>
            <span width="50%"><h5>Designation : {{faculty.designation}}</h5></span>
          </div>
          <br>
          <hr>
          <h5>Your Proctees</h5>
          <br />
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th scope="col">Sl.no</th>
                  <th scope="col">USN</th>
                  <th scope="col">Name</th>
                  <th scope="col">Sem</th>
                </tr>
              </thead>
              
                <tbody>
                  {% for student in students %}
                  <tr>
                    <td>{{forloop.counter}}</td>
                    <td><a href="{% url 'faculty:student-details' student.USN %}" style="cursor: pointer; text-decoration: none;">{{student.USN}}</a></td>
                    <td>{{student.name}}</td>
                    <td>{% if student.current_sem != None %}
                      {{student.current_sem}}
                      {% else %}
                      No sem added!
                      {% endif %}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              
            </table>
          </div>
    </main>
  </div>
</div>

{% endblock content %}

CSE_site/templates/faculty_dashboard_proctor/send_fill.html
From your proctor.
{{message}}

Regards
{{name}}

CSE_site/templates/faculty_dashboard_proctor/student_details.html
{% extends '../base.html' %} {% load static %} {% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    {% if s_info == 0 %}
    <div class="position" style="margin-bottom: 2%; width: 70%;">
        <form method="post" action="{% url 'faculty:student-details' usn %}">
            {% csrf_token %}
            <input class="form-control border" name='email' value='{{email}}' type="text" id="exampleInputEmail1" aria-describedby="emailHelp"  readonly>
        <br />
        <input class="form-control border" name='email-text' value='Please fill your personal details as soon as possible!!' type='text' id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Message">    
        <br />
        <div>
            <button style="background-color: #1b62bf; border: none; width: 100%; border-radius: 5px; padding: 1%; color: white" type="submit">Send Email</button>
        </div>
        </form>
    </div>
    {% else %}
<div class="main_details">
    <h3 >Student Details</h3>
  </div>
  <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"
      >
        <!-- <h1 class="h2">Dashboard</h1> -->
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button class="website notification" style="padding: 1%">
              <a
                style="text-decoration: none"
                href="{% url 'faculty:custom-form' %}"
              >
                <span>Send email to parents</span
                ><span class="badge">{{req}}</span></a
              >
            </button>
          </div>
        </div>
  <br />
      </div>
  <div class=" mb-2 mb-md-0">
    <div class="btn-group">
      <span><h4 class="text">Personal</h4></span>
      {% if not s_info.isApproved %}
      <button style="padding: 5%; margin-left: 10%; color: white; border: none; background-color: #009933; border-radius: 10px;">
        <a
          style="text-decoration: none; color: white;"
          href="{% url 'faculty:student-details-approve' s_info.USN %}"
          ><span>Approve</span></a
        >
      </button>
      {% endif %}
    </div>
  </div>
</div>
  <br/>
  <table class="table">
    <tbody>
      <tr>
        <th>Mobile Number</th>
        <th>Email Address</th>
        <th>Date of Birth</th>
        <th>Blood Group</th>
      </tr>
      <tr>
        <td>{{s_info.phone_number}}</td>
        <td>{{email}}</td>
        <td>{{s_info.date_of_birth}}</td>
        <td>{{s_info.blood_group}}</td>
      </tr>
    </tbody>
  </table>
  <table class="table">
    <tbody>
      <tr>
        <th width="40%">Permanent Address</th>
        <th width="40%">Present Address</th>
      </tr>
      <tr>
        <td>{{s_info.permanent_address}}</td>
        <td>{{s_info.current_address}}</td>
      </tr>
    </tbody>
  </table>
  <br />
  <h5 class="text">Parent Details</h5>
  <table class="table">
    <tbody>
      <tr>
        <th width="20%">Details</th>
        <th width="40%">Father / Guardian</th>
        <th width="40%">Mother</th>
      </tr>
      <tr>
        <th>Name</th>
        <td>{{s_info.father_name}}</td>
        <td>{{s_info.mother_name}}</td>
      </tr>
      <tr>
        <th>Occupation</th>
        <td>{{s_info.father_occupation}}</td>
        <td>{{s_info.mother_occupation}}</td>
      </tr>
      <tr>
        <th>Mobile</th>
        <td>{{s_info.father_phone_number}}</td>
        <td>{{s_info.mother_phone_number}}</td>
      </tr>
      <tr>
        <th>Email</th>
        <td>{{s_info.father_email}}</td>
        <td>{{s_info.mother_email}}</td>
      </tr>
    </tbody>
  </table>
  <br />
  <h5 class="text">Qualifying Examination</h5>
  <table class="table">
    <tbody>
      <tr>
        <th width="20%">Details</th>
        <th width="40%">Class X/SSC</th>
        <th width="40%">Class XII/ PUC</th>
      </tr>
      <tr>
        <th>Institute Name</th>
        <td>{{s_info.class_10th_school}}</td>
        <td>{{s_info.class_12th_school}}</td>
      </tr>
      <tr>
        <th>Board</th>
        <td>{{s_info.class_10th_board}}</td>
        <td>{{s_info.class_12th_board}}</td>
      </tr>
      <tr>
        <th>Percentage</th>
        <td>{{s_info.class_10th_percentage}}</td>
        <td>{{s_info.class_12th_percentage}}</td>
      </tr>
      <tr>
        <th>Year of Passing</th>
        <td>{{s_info.class_10th_year}}</td>
        <td>{{s_info.class_12th_year}}</td>
      </tr>
    </tbody>
  </table>
  <br />

  <h5 class="text">Courses registered for semester {{sem}}</h5>
  <br />
  {% if cour %}
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">Sl.no</th>
          <th scope="col">Course Code</th>
          <th scope="col">Course Name</th>
          <th scope="col">Credits</th>
          <th scope="col">Registration Type</th>
          <th scope="col">{% if not_ap %}
            <button style="padding: 5%; margin-left: 10%; color: white; box-shadow: 1px 5px 15px 3px rgba(133,191,153,1); border: none; background-color: #009933; border-radius: 10px; margin-bottom: 2%;">
              <a
                style="text-decoration: none; color: white;"
                href="{% url 'faculty:student-course-approve' s_info.USN 0 %}"
                ><span>Approve All</span></a
              >
            </button>
            {% endif %}</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for course in courses %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{course.courseCode}}</td>
          <td>{{course.courseName}}</td>
          <td>{{course.credit}}</td>
          <td>{{course.registration}}</td>
          {% if not course.is_approved %}
          <td>
            <button style="padding: 5%; margin-left: 10%; color: white; border: none; background-color: #009933; border-radius: 10px;">
                <a
                style="text-decoration: none; color: white;"
                href="{% url 'faculty:student-course-approve' s_info.USN course.courseCode %}"
                ><span>Approve</span></a
              >
            </button>
            
          </td>
          <td>
            <div style="padding: 2%;">
                <button style="padding: 7%; margin-left: 10%; color: white; border: none; background-color: #BF0404; border-radius: 10px;">
                    <a
                    style="text-decoration: none; color: white;"
                    href="{% url 'faculty:student-course-reject' email %}"
                    ><span>Reject</span></a
                  >
                  </button>
              </div>
          </td>
          {% endif %}

        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  <div style="width: 25%; height: 10%;">
    <button style="padding: 5%; margin-left: 10%; color: white; box-shadow: 1px 5px 15px 3px rgba(133,191,153,1); border: none; background-color: #009933; border-radius: 10px; margin-bottom: 2%;">
      <a
        style="text-decoration: none; color: white;"
        href="{% url 'faculty:student-alert' email %}"
        ><span>Send Mail</span></a
      >
    </button>
  </div>
  {% endif %}
  <br>
  <h5 class="text">Fastrack Details</h5>
  <br />
  <div class="table-responsive">
    {% if fast_count == 0 %}
    <div style="margin-left: 5%; margin-bottom: 5%; padding: 2%; background-color: #b3ffb3; border-radius: 25px; width: 25%; border: 1px solid #00e600">
      <h6>No Fastrack</h6>
    </div>
    {% else %}
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">Sl.no</th>
          <th scope="col">Course Code</th>
          <th scope="col">Course Name</th>
          <th scope="col">Credits</th>
          <th scope="col">Sem</th>
          <th scope="col">Attempt Number</th>
        </tr>
      </thead>
      <tbody>
        {% for course in fastrack %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{course.courseCode}}</td>
          <td>{{course.courseName}}</td>
          <td>{{course.credit}}</td>
          <td>{{course.sem}}</td>
          <td>{{course.attemptNumber}}</td>
          {% if not course.is_approved %}
          <td>
            <button style="padding: 5%; margin-left: 10%; color: white; border: none; background-color: #009933; border-radius: 10px;">
                <a
                style="text-decoration: none; color: white;"
                href="{% url 'faculty:student-fcourse-approve' s_info.USN course.courseCode %}"
                ><span>Approve</span></a
              >
            </button>
            
          </td>
          <td>
            <div style="padding: 2%;">
                <button style="padding: 7%; margin-left: 10%; color: white; border: none; background-color: #BF0404; border-radius: 10px;">
                    <a
                    style="text-decoration: none; color: white;"
                    href="{% url 'faculty:student-fcourse-reject' email %}"
                    ><span>Reject</span></a
                  >
                  </button>
              </div>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table><br>
    {% endif %}
  </div>
  <h5 class="text"> Academic Details </h5>
  <div style="width: 25%; height: 5%;">
    <button style="padding: 5%; margin-left: 10%; color: white; border: none; box-shadow: 1px 5px 15px 3px rgba(133,191,153,1); background-color: #009933; border-radius: 10px; margin-bottom: 2%;">
      <a
        style="text-decoration: none; color: white;"
        href="{% url 'student:marks' s_info.USN  %}"
        ><span>View Academic Details</span></a
      >
    </button>
  </div>
  {% endif %}
</main>
{% endblock content %}