CSE_site/CSE_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', views.landing_page, name='landing_page'),
    path('exam_room_allocator/', include('online_cie_allocator.urls')),
    path('', include('authentication.urls')),
    path('notes_and_qp_mgmt/', include('notes_and_qp_mgmt.urls')),
    path('student/', include('student_dashboard_proctor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CSE_site/student_dashboard_proctor/urls.py
from django.urls import path,include
from . import views

app_name = 'student'

urlpatterns = [
    path('/dashboard/<str:pk>/', views.dashboard, name="dashboard"),
    path('/marks/<str:pk>/', views.dashboard_marks, name="marks"),
    path('/courses/register/', views.registerCourses, name='register'),
    path('/add_student_details/', views.studentDetails, name='student_details_form'),
    path('/courses/edit/', views.editCourseDetails, name='edit'),
    path('/courses/update/', views.updateCourseDetails, name='update'),
    path("/no_proctor", views.no_proc, name="no_proctor"),
    path("/courses/fastrack/register", views.registerFastrack, name="fastrack_register"),
]

CSE_site/student_dashboard_proctor/forms.py
from django.forms import ModelForm
from . import models
from .models import StudentDetail
from django import forms

class Courses(models.Sem):
    o=5


class StudentDetailsForm(ModelForm):
    class Meta:
        model= StudentDetail
        fields= 'USN','father_name','mother_name','date_of_birth','permanent_address','current_address','phone_number','blood_group','father_occupation','mother_occupation','father_phone_number','mother_phone_number','father_email','mother_email','guardian_name','guardian_phone_number','guardian_email','class_10th_school','class_10th_board','class_10th_percentage','class_10th_year','class_12th_school','class_12th_board','class_12th_percentage','class_12th_year','class_Diploma_school','class_Diploma_board','class_Diploma_percentage','class_Diploma_year'
        widgets = {
            'USN': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'father_name': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'mother_name': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'permanent_address': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'current_address': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'phone_number': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'blood_group': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'father_occupation': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'mother_occupation': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'father_phone_number': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'mother_phone_number': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'father_email': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'mother_email': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'guardian_name': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'guardian_phone_number': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'guardian_email': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'class_10th_school': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'class_10th_board': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'class_10th_percentage': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'class_10th_year': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'class_12th_school': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'class_12th_board': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'class_12th_percentage': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'class_12th_year': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'class_Diploma_school': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'class_Diploma_board': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'class_Diploma_percentage': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
            'class_Diploma_year': forms.TextInput(attrs={'class': 'position form-control border','style':'margin-bottom: 1%; width: 80%;'}),
        }

CSE_site/student_dashboard_proctor/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from . import models
from student_dashboard_proctor.models import Student, courseRequest, Sem, StudentDetail, Fastrack
from .forms import StudentDetailsForm
from django.db.models import Count
from django.forms import formset_factory

# Create your views here.
@login_required
def dashboard(request, pk):
    student=Student.objects.get(email=request.user.email)
    if(StudentDetail.objects.filter(USN=student.USN).exists()):
        s_info = StudentDetail.objects.get(USN=student.USN)
    else:
        s_info = 0
    number=courseRequest.objects.filter(student_usn=student.USN)
    sem=student.current_sem
    if(pk!=student.USN):
        return HttpResponse("Not allowd")
    courses = models.Sem.objects.filter(USN=pk, sem=sem)
    coursess=Sem.objects.filter(USN=pk, sem=sem, is_approved=False)
    fastrack = models.Fastrack.objects.filter(USN=pk, is_active=True)
    length = fastrack.count()
    fcourses = models.Fastrack.objects.filter(USN=pk, is_active=True, is_approved=False)
    context = {'courses': courses, 'req': number.count(), 'sem': sem, 's_info': s_info, 'student': student, 'usn': student.USN, 'fast_count': length, 'fastrack': fastrack, 'fcourses':fcourses, 'unapproved': len(coursess)}
    return render(request, 'student_dashboard_proctor/dashboard.html', context)


@login_required
def dashboard_marks(request, pk):
    student=Student.objects.get(USN=pk)
    number=courseRequest.objects.filter(student_usn=student.USN)
    sem=student.current_sem
    if(pk!=student.USN):
        return HttpResponse("Not allowd")
    courses = models.Sem.objects.filter(USN=pk)
    sem = set()
    for co in courses:
        sem.add(co.sem)
    context = {'courses': courses, 'req': number.count(), 'sems':sem}
    return render(request, 'student_dashboard_proctor/course_marks.html', context)

@login_required
def registerCourses(request):
    o=0
    student=Student.objects.get(email=request.user.email)
    if courseRequest.objects.count() > 0:
        if courseRequest.objects.exists():
            number=courseRequest.objects.filter(student_usn=student.USN)
            if number.count() >0:
                numbers=number.get(student_usn=student.USN)
                sem=numbers.sem
                o=numbers.no_subjects
    no=[]
    if request.method=="POST":
        while o>0:
            ccode="".join(request.POST['code%s' %(o)].rstrip())
            cname=request.POST['name%s' %(o)]
            credit=request.POST['credits%s' %(o)]
            registration=request.POST['reg%s' %(o)]
            attempt=request.POST['attempt%s' %(o)]
            semob = Sem(USN=student.USN, sem=sem, courseName=cname, courseCode=ccode, credit=credit, registration=registration, attemptNumber=attempt)
            semob.save()
            o-=1
        numbers.delete()
        return redirect( 'student:dashboard', pk=student.USN)
    while o>0:
        no.append(o)
        o-=1
    print(no, o)
    
    context = {'usn': student.USN, 'number': no, 'count': len(no)}
    return render(request, 'student_dashboard_proctor/course_register_form.html', context)

@login_required
def studentDetails(request):
    student=Student.objects.get(email=request.user.email)
    if(StudentDetail.objects.filter(USN=student.USN).exists()):
        s_info = StudentDetail.objects.get(USN=student.USN)
    else:
        s_info = 0
    print(s_info)
    submitted = False
    if request.method == 'POST':
        form = StudentDetailsForm(request.POST,request.FILES, instance=student)
        if form.is_valid():
            form.instance.user = student
            form.save()
            obj=form.cleaned_data
            studeob=StudentDetail(USN=obj['USN'], father_name=obj['father_name'], mother_name=obj['mother_name'], date_of_birth=obj['date_of_birth'], permanent_address=obj['permanent_address'], current_address=obj['current_address'], phone_number=obj['phone_number'],
                                  blood_group=obj['blood_group'], father_occupation=obj['father_occupation'], mother_occupation=obj['mother_occupation'], father_phone_number=obj['father_phone_number'], mother_phone_number=obj['mother_phone_number'], 
                                  father_email=obj['father_email'], mother_email=obj['mother_email'], guardian_name=obj['guardian_name'], guardian_email=obj['guardian_email'], guardian_phone_number=obj['guardian_phone_number'],
                                  class_10th_school=obj['class_10th_school'], class_10th_percentage=obj['class_10th_percentage'], class_10th_board=obj['class_10th_board'], class_10th_year=obj['class_10th_year'], 
                                  class_12th_school=obj['class_12th_school'], class_12th_percentage=obj['class_12th_percentage'], class_12th_board=obj['class_12th_board'], class_12th_year=obj['class_12th_year'], 
                                  class_Diploma_school=obj['class_Diploma_school'], class_Diploma_percentage=obj['class_Diploma_percentage'], class_Diploma_board=obj['class_Diploma_board'], class_Diploma_year=obj['class_Diploma_year'], 
                                  )
            #print(form.cleaned_data)
            studeob.save()
            return HttpResponseRedirect('/student/add_student_details/?submitted=True')
    else:
        if s_info != 0 :
            form = StudentDetailsForm(instance=s_info)
        else :
            form = StudentDetailsForm()
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'student_dashboard_proctor/student_details_form.html', {'form':form, 'submitted':submitted, 's_info':s_info, 'usn': student.USN})


@login_required
def editCourseDetails(request):
    student=Student.objects.get(email=request.user.email)
    coursess=Sem.objects.filter(USN=student.USN, sem=student.current_sem)
    o=1
    if request.method=="POST":
        for course in coursess:
            if course.is_approved :
                print(course)
                continue
            else:
                course.courseCode=request.POST['code%s' %(o)]
                course.courseName=request.POST['name%s' %(o)]
                course.credit=request.POST['credits%s' %(o)]
                course.registration=request.POST['reg%s' %(o)]
                course.attemptNumber=request.POST['attempt%s' %(o)]
                course.save()
                o+=1
        return redirect( 'student:dashboard', pk=student.USN)
    else:
        courses = []
        for cor in coursess:
            if cor.is_approved :
                continue
            else:
                courses.append(cor)
            
    context={'courses': courses}
    return render(request, 'student_dashboard_proctor/course_edit_form.html', context)

@login_required
def updateCourseDetails(request):
    student=Student.objects.get(email=request.user.email)
    courses=Sem.objects.filter(USN=student.USN, sem=student.current_sem)
    o=courses.count()
    if request.method=="POST":
        for course in courses:
            attendence=float(request.POST['attendance%s' %(o)])
            cie=float(request.POST['cie%s' %(o)])
            see=float(request.POST['see%s' %(o)])
            gradepoints=float(request.POST['gp%s' %(o)])
            if attendence>100 or attendence<0 or cie>50 or cie<0 or see>100 or see<0 or gradepoints<0 or gradepoints>10:
                messages.add_message(request, messages.ERROR,'Enter proper details!')
                return redirect('student:update')
            course.attendance=attendence
            course.CIE=cie
            course.SEE=see
            course.GradePoints=gradepoints
            course.save()
            o-=1
        return redirect( 'student:dashboard', pk=student.USN)
    context={'courses': courses}
    return render(request, 'student_dashboard_proctor/course_update_form.html', context)

def no_proc(request):
    return render(request, 'student_dashboard_proctor/no_proctor.html')

@login_required
def registerFastrack(request):
    student = Student.objects.get(email=request.user.email)
    if request.method == "POST":
        num_subjects = int(request.POST.get('fastrack_subjects'))
        o=num_subjects
        for i in range(1, num_subjects+1):
            ccode="".join(request.POST['code%s' %(o)].rstrip())
            sem=int(request.POST['sem%s' %(o)])
            cname=request.POST['name%s' %(o)]
            credit=request.POST['credits%s' %(o)]
            attempt=request.POST['attempt%s' %(o)]
            registration=request.POST['reg%s' %(o)]
            # last_attempt = Sem.objects.filter(
            #     USN=student.USN,
            #     sem=student.current_sem,
            #     courseCode=ccode
            # )
            # # Increment the attempt number
            # attempt = last_attempt.attemptNumber + 1 if last_attempt else 1
            fastrackob = Fastrack(USN=student.USN, sem=sem, courseName=cname, courseCode=ccode, credit=credit, registration=registration, attemptNumber=attempt)
            fastrackob.save()
        return redirect('student:dashboard', pk=student.USN)
    else:
        context = {'usn': student.USN, 'number': range(1, 5)}
        return render(request, 'student_dashboard_proctor/fastrack_course_register_form.html', context)

CSE_site/templates/student_dashboard_proctor/dashboard.html
{% extends '../base.html' %} {% load static %} {% block content %}
<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }

  .b-example-divider {
    height: 3rem;
    background-color: rgba(0, 0, 0, 0.1);
    border: solid rgba(0, 0, 0, 0.15);
    border-width: 1px 0;
    box-shadow: inset 0 0.5em 1.5em rgba(0, 0, 0, 0.1),
      inset 0 0.125em 0.5em rgba(0, 0, 0, 0.15);
  }

  .b-example-vr {
    flex-shrink: 0;
    width: 1.5rem;
    height: 100vh;
  }

  .bi {
    vertical-align: -0.125em;
    fill: currentColor;
  }

  .nav-scroller {
    position: relative;
    z-index: 2;
    height: 2.75rem;
    overflow-y: hidden;
  }

  .nav-scroller .nav {
    display: flex;
    flex-wrap: nowrap;
    padding-bottom: 1rem;
    margin-top: -1px;
    overflow-x: auto;
    text-align: center;
    white-space: nowrap;
    -webkit-overflow-scrolling: touch;
  }
  .feather {
    width: 16px;
    height: 16px;
  }

  /*
        * Sidebar
        */

  .sidebar {
    position: fixed;
    top: 0;
    /* rtl:raw:
        right: 0;
        */
    bottom: 0;
    /* rtl:remove */
    left: 0;
    z-index: 100; /* Behind the navbar */
    padding: 48px 0 0; /* Height of navbar */
    box-shadow: inset -1px 0 0 rgba(0, 0, 0, 0.1);
  }

  @media (max-width: 767.98px) {
    .sidebar {
      top: 5rem;
    }
  }

  .sidebar-sticky {
    height: calc(100vh - 48px);
    overflow-x: hidden;
    overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
  }

  .sidebar .nav-link {
    font-weight: 500;
    color: #333;
  }

  .sidebar .nav-link .feather {
    margin-right: 4px;
    color: #727272;
  }

  .sidebar .nav-link.active {
    color: #2470dc;
  }

  .sidebar .nav-link:hover .feather,
  .sidebar .nav-link.active .feather {
    color: inherit;
  }

  .sidebar-heading {
    font-size: 0.75rem;
  }

  /*
        * Navbar
        */

  .navbar-brand {
    padding-top: 0.75rem;
    padding-bottom: 0.75rem;
    background-color: rgba(0, 0, 0, 0.25);
    box-shadow: inset -1px 0 0 rgba(0, 0, 0, 0.25);
  }

  .navbar .navbar-toggler {
    top: 0.25rem;
    right: 1rem;
  }

  .navbar .form-control {
    padding: 0.75rem 1rem;
  }

  .form-control-dark {
    color: #fff;
    background-color: rgba(255, 255, 255, 0.1);
    border-color: rgba(255, 255, 255, 0.1);
  }

  .form-control-dark:focus {
    border-color: transparent;
    box-shadow: 0 0 0 3px rgba(255, 255, 255, 0.25);
  }
  .notification {
    color: white;
    text-decoration: none;
    padding: 15px 26px;
    position: relative;
    display: inline-block;
  }

  .notification .badge {
    position: absolute;
    top: -10px;
    right: -10px;
    padding: 5px 10px;
    border-radius: 50%;
    background-color: red;
    color: white;
  }
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }

  td,
  th {
    border: 1px solid #eef3fe;
    text-align: left;
    padding: 8px;
  }

  tr:nth-child(even) {
    background-color: #e0e6f9;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md bg-light">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">
            <span data-feather="home" class="align-text-bottom"></span>
            Dashboard
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'student:marks' usn  %}">
            <span data-feather="file" class="align-text-bottom"></span>
            Academic Details
          </a>
        </li>
      </ul>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      {% if s_info == 0 %}
      <div class="center" style="padding: 10%">
        <div
          class="container"
          style="
            background-color: #c0daf1;
            padding: 5%;
            border: 1px solid #205d92;
            border-radius: 25px;
          "
        >
          <h4 style="color: #205d92; font-family: 'Sono', sans-serif">
            Please enter your personal details!!
            <A href="{% url 'student:student_details_form'   %}">Here</a>
          </h4>
        </div>
      </div>
      {%else%}
      <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"
      >
        <!-- <h1 class="h2">Dashboard</h1> -->
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button class="website notification" style="padding: 1%">
              <a
                style="text-decoration: none"
                href="{% url 'student:register' %}"
              >
                <span>Register Courses</span
                ><span class="badge">{{req}}</span></a
              >
            </button>
            <button class="website notification" style="padding: 1%">
              <a
                style="text-decoration: none"
                href="{% url 'student:student_details_form' %}"
                ><span>Add/Edit Student Details</span></a
              >
            </button>
            <button class="website notification" style="padding: 1%">
              <a
                style="text-decoration: none"
                href="{% url 'student:fastrack_register' %}"
              >
                <span>Register for Fastrack</span
                ><span class="badge">{{req}}</span></a
              >
            </button>
            {% if unapproved != 0 %}
            <button class="website notification" style="padding: 1%">
              <a
                style="text-decoration: none"
                href="{% url 'student:edit' %}"
                ><span>Update Courses</span></a
              >
            </button>
            {% endif %}
          </div>
        </div>
      </div>
      <!-- <h4>Student Information</h4> -->
      <div class="main_details">
        <span width="50%"><h5>Name : {{student.name}}</h5></span>
        <span width="50%"><h5>USN : {{student.USN}}</h5></span>
        <span width="50%"><h5>Proctor : {{student.proctor_id}}</h5></span>
      </div>
      <br />
      <table class="table">
        <tbody>
          <tr>
            <th>Mobile Number</th>
            <th>Email Address</th>
            <th>Date of Birth</th>
            <th>Blood Group</th>
          </tr>
          <tr>
            <td>{{s_info.phone_number}}</td>
            <td>{{student.email}}</td>
            <td>{{s_info.date_of_birth}}</td>
            <td>{{s_info.blood_group}}</td>
          </tr>
        </tbody>
      </table>
      <table class="table">
        <tbody>
          <tr>
            <th width="40%">Permanent Address</th>
            <th width="40%">Present Address</th>
          </tr>
          <tr>
            <td>{{s_info.permanent_address}}</td>
            <td>{{s_info.current_address}}</td>
          </tr>
        </tbody>
      </table>
      <br />
      <h5>Parent Details</h5>
      <table class="table">
        <tbody>
          <tr>
            <th width="20%">Details</th>
            <th width="40%">Father / Guardian</th>
            <th width="40%">Mother</th>
          </tr>
          <tr>
            <th>Name</th>
            <td>{{s_info.father_name}}</td>
            <td>{{s_info.mother_name}}</td>
          </tr>
          <tr>
            <th>Occupation</th>
            <td>{{s_info.father_occupation}}</td>
            <td>{{s_info.mother_occupation}}</td>
          </tr>
          <tr>
            <th>Mobile</th>
            <td>{{s_info.father_phone_number}}</td>
            <td>{{s_info.mother_phone_number}}</td>
          </tr>
          <tr>
            <th>Email</th>
            <td>{{s_info.father_email}}</td>
            <td>{{s_info.mother_email}}</td>
          </tr>
        </tbody>
      </table>
      <br />
      <h5>Qualifying Examination</h5>
      <table class="table">
        <tbody>
          <tr>
            <th width="20%">Details</th>
            <th width="40%">Class X/SSC</th>
            <th width="40%">Class XII/ PUC</th>
          </tr>
          <tr>
            <th>Institute Name</th>
            <td>{{s_info.class_10th_school}}</td>
            <td>{{s_info.class_12th_school}}</td>
          </tr>
          <tr>
            <th>Board</th>
            <td>{{s_info.class_10th_board}}</td>
            <td>{{s_info.class_12th_board}}</td>
          </tr>
          <tr>
            <th>Percentage</th>
            <td>{{s_info.class_10th_percentage}}</td>
            <td>{{s_info.class_12th_percentage}}</td>
          </tr>
          <tr>
            <th>Year of Passing</th>
            <td>{{s_info.class_10th_year}}</td>
            <td>{{s_info.class_12th_year}}</td>
          </tr>
        </tbody>
      </table>
      <br />

      <h5>Courses registered for semester {{sem}}</h5>
      <br />
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Sl.no</th>
              <th scope="col">Course Code</th>
              <th scope="col">Course Name</th>
              <th scope="col">Credits</th>
              <th scope="col">Registration Type</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            {% for course in courses %}
            <tr>
              <td>{{forloop.counter}}</td>
              <td>{{course.courseCode}}</td>
              <td>{{course.courseName}}</td>
              <td>{{course.credit}}</td>
              <td>{{course.registration}}</td>
              <td>
                {% if course.is_approved %}
                <button style="padding: 2%; margin-left: 10%; color: white; border: none; background-color: #00e600; border-radius: 10px;">
                <span>Approved</span>
                </button>
                {% else %}
                <div style="padding: 2%;">
                  <button style="padding: 2%; margin-left: 10%; color: white; border: none; background-color: #BF0404; border-radius: 10px;">
                    <span><h6>Waiting for Approval</h6></span>
                    </button>
                </div>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <h5>Fastrack Details</h5>
      <br />
      <div class="table-responsive">
        {% if fast_count == 0 %}
        <div style="margin-left: 5%; margin-bottom: 5%; padding: 2%; background-color: #b3ffb3; border-radius: 25px; width: 25%; border: 1px solid #00e600">
          <h6>You don't have any Fastrack</h6>
        </div>
        {% else %}
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Sl.no</th>
              <th scope="col">Course Code</th>
              <th scope="col">Course Name</th>
              <th scope="col">Credits</th>
              <th scope="col">Sem</th>
              <th scope="col">Attempt Number</th>
            </tr>
          </thead>
          <tbody>
            {% for course in fcourses %}
            <tr>
              <td>{{forloop.counter}}</td>
              <td>{{course.courseCode}}</td>
              <td>{{course.courseName}}</td>
              <td>{{course.credit}}</td>
              <td>{{course.sem}}</td>
              <td>{{course.attemptNumber}}</td>
              <td>
                {% if course.is_approved %}
                <button style="padding: 2%; margin-left: 10%; color: white; border: none; background-color: #00e600; border-radius: 10px;">
                <span>Approved</span>
                </button>
                {% else %}
                <div style="padding: 2%;">
                  <button style="padding: 2%; margin-left: 10%; color: white; border: none; background-color: #BF0404; border-radius: 10px;">
                    <span><h6>Waiting for Approval</h6></span>
                    </button>
                </div>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% endif %}
      </div>
      {% endif %}
    </main>
  </div>
</div>

{% endblock content %}

<!-- <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>
   -->

CSE_site/templates/student_dashboard_proctor/no_proctor.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="center" style="padding: 10%;">
    <div class="container" style="background-color: #fdb4b4; padding: 5%; border-radius: 25px;">
        <h4 style="color: #fb3737; font-family: 'Sono', sans-serif">
            You don't have a proctor yet, if you think its a mistake, please contact CS office
        </h4>
    </div>
</div>
{% endblock content %}